# Generated by Django 4.2.7 on 2026-09-27 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('data_reserva', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data da Reserva')),
                ('status', models.CharField(choices=[('A', 'Aguardando'), ('C', 'Confirmada'), ('E', 'Expirada'), ('F', 'Finalizada'), ('X', 'Cancelada')], db_index=True, default='A', max_length=1, verbose_name='Status')),
                ('posicao_fila', models.IntegerField(default=0, verbose_name='Posição na Fila')),
                ('notificado', models.BooleanField(default=False, verbose_name='Notificado')),
                ('data_notificacao', models.DateTimeField(blank=True, null=True, verbose_name='Data da Notificação')),
                ('data_expiracao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Expiração')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='acervo.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['data_reserva'],
                'indexes': [models.Index(fields=['status', 'posicao_fila'], name='reservas_re_status_c6ad8a_idx'), models.Index(fields=['data_reserva'], name='reservas_re_data_re_2f7e2c_idx')],
                'unique_together': {('livro', 'usuario')},
            },
        ),
    ]
