# Generated by Django 4.2.7 on 2026-09-27 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DOACAO', 'Doação de Livro'), ('EMPRESTIMO', 'Empréstimo Realizado'), ('DEVOLUCAO', 'Devolução no Prazo'), ('AVALIACAO', 'Avaliação de Livro'), ('CADASTRO', 'Cadastro na Plataforma'), ('CONVITE', 'Convite de Amigo'), ('LEITURA', 'Registro de Leitura'), ('RESENHA', 'Publicação de Resenha')], max_length=20, unique=True, verbose_name='Tipo')),
                ('pontos', models.IntegerField(default=0, verbose_name='Pontos')),
                ('descricao', models.CharField(blank=True, max_length=200, verbose_name='Descrição')),
                ('icone', models.CharField(blank=True, max_length=10, verbose_name='Ícone')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'ordering': ['tipo'],
            },
        ),
        migrations.CreateModel(
            name='PontuacaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_totais', models.IntegerField(db_index=True, default=0, verbose_name='Pontos Totais')),
                ('nivel', models.IntegerField(default=1, verbose_name='Nível')),
                ('titulo', models.CharField(default='Novo Explorador', max_length=50, verbose_name='Título')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pontuacao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pontuação',
                'verbose_name_plural': 'Pontuações',
                'ordering': ['-pontos_totais'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPontos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.IntegerField(verbose_name='Pontos')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Objeto')),
                ('content_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Objeto')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gamificacao.acao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_pontos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Pontos',
                'verbose_name_plural': 'Históricos de Pontos',
                'ordering': ['-data'],
            },
        ),
    ]
