# Generated by Django 4.2.7 on 2026-09-27 00:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('cep', models.CharField(blank=True, help_text='Apenas números', max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
                ('titulo', models.CharField(db_index=True, max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=200, verbose_name='Subtítulo')),
                ('autor', models.CharField(db_index=True, max_length=200, verbose_name='Autor')),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=17, verbose_name='ISBN')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('capa', models.ImageField(blank=True, null=True, upload_to='capas/%Y/%m/', verbose_name='Capa')),
                ('capa_url', models.URLField(blank=True, max_length=500, verbose_name='URL da Capa')),
                ('resumo', models.TextField(blank=True, verbose_name='Resumo/Sinopse')),
                ('editora', models.CharField(blank=True, max_length=100, verbose_name='Editora')),
                ('ano_publicacao', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2026)], verbose_name='Ano de Publicação')),
                ('paginas', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de Páginas')),
                ('genero', models.CharField(choices=[('FIC', 'Ficção'), ('NAO', 'Não-ficção'), ('ROM', 'Romance'), ('FAN', 'Fantasia'), ('FIC_CI', 'Ficção Científica'), ('MIS', 'Mistério'), ('SUS', 'Suspense'), ('TER', 'Terror'), ('AVE', 'Aventura'), ('POE', 'Poesia'), ('DRA', 'Drama'), ('BIO', 'Biografia'), ('AUT', 'Autobiografia'), ('HIS', 'História'), ('CIE', 'Ciência'), ('TEC', 'Tecnologia'), ('FIL', 'Filosofia'), ('REL', 'Religião'), ('AAJ', 'Auto-ajuda'), ('DEP', 'Desenvolvimento Pessoal'), ('EDU', 'Educação'), ('PSI', 'Psicologia'), ('SAU', 'Saúde'), ('INF', 'Infantil'), ('JUV', 'Juvenil'), ('HQS', 'HQs e Mangás'), ('OUT', 'Outros')], db_index=True, default='OUT', max_length=20, verbose_name='Gênero')),
                ('idioma', models.CharField(default='pt-BR', max_length=10, verbose_name='Idioma')),
                ('status', models.CharField(choices=[('DD', 'Disponível para Doação'), ('DE', 'Disponível para Empréstimo'), ('RE', 'Reservado'), ('EM', 'Emprestado'), ('IN', 'Indisponível')], db_index=True, default='DD', max_length=2, verbose_name='Status')),
                ('tipo_midia', models.CharField(choices=[('FI', 'Físico'), ('DI', 'Digital'), ('AU', 'Audiolivro'), ('EB', 'E-book')], default='FI', max_length=2, verbose_name='Tipo de Mídia')),
                ('possui_braille', models.BooleanField(default=False, verbose_name='Disponível em Braille')),
                ('possui_fonte_ampliada', models.BooleanField(default=False, verbose_name='Disponível em Fonte Ampliada')),
                ('possui_audio', models.BooleanField(default=False, verbose_name='Disponível em Áudio')),
                ('possui_formato_digital_acessivel', models.BooleanField(default=False, help_text='PDF/EPUB acessível para leitores de tela', verbose_name='Formato Digital Acessível')),
                ('arquivo_digital', models.FileField(blank=True, null=True, upload_to='livros_digitais/%Y/%m/', verbose_name='Arquivo Digital')),
                ('arquivo_audio', models.FileField(blank=True, null=True, upload_to='audiolivros/%Y/%m/', verbose_name='Arquivo de Áudio')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/%Y/%m/', verbose_name='QR Code')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data de Cadastro')),
                ('doador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros_doados', to=settings.AUTH_USER_MODEL, verbose_name='Doador')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Atualizado em')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentário')),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Data da Avaliação')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='acervo.livro', verbose_name='Livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.AddIndex(
            model_name='livro',
            index=models.Index(fields=['titulo'], name='acervo_livr_titulo_ac04b7_idx'),
        ),
        migrations.AddIndex(
            model_name='livro',
            index=models.Index(fields=['autor'], name='acervo_livr_autor_fa8875_idx'),
        ),
        migrations.AddIndex(
            model_name='livro',
            index=models.Index(fields=['isbn'], name='acervo_livr_isbn_4a5e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='livro',
            index=models.Index(fields=['genero'], name='acervo_livr_genero_d5ea18_idx'),
        ),
        migrations.AddIndex(
            model_name='livro',
            index=models.Index(fields=['status'], name='acervo_livr_status_42d3d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('livro', 'usuario')},
        ),
    ]
